### ISSUE TITLE
Change format in input

### ISSUE THREAD

**Issue by hdkcreative** [iTorongo/ng-month-picker#12]
HI @iTorongo , is possible change this format ? 
any sintaxys for this  ?
![image](https://user-images.githubusercontent.com/18191896/102506772-3a0f8380-4062-11eb-996b-5de31f003171.png)

**Comment by iTorongo** [comment]
@hdkcreative  
Yes, you can. You can change the display format as well as value format.
For changing display format we have input property `displayFormat`
For changing value format we have input property `valueFormat`
Use `<ng-month-picker  [displayFormat]="'MM/YYYY'" [(ngModel)]="currentMonth"></ng-month-picker>` for your desired format.
I will update the readme soon.
Thanks
