### ISSUE TITLE
ERROR in ./node_modules/ng-month-picker/fesm5/ng-month-picker.js

### ISSUE THREAD

**Issue by swapnildalvi2002** [iTorongo/ng-month-picker#8]
WARNING in ./node_modules/ng-month-picker/fesm5/ng-month-picker.js 21:62-80
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

ERROR in ./node_modules/ng-month-picker/fesm5/ng-month-picker.js
Module not found: Error: Can't resolve 'moment' in '/home/web-app/node_modules/ng-month-picker/fesm5'

By following the steps mentioned.

**Comment by iTorongo** [comment]
@swapnildalvi2002 Hopefully I will upgrade it to angular version 10 in the next few days and this will be fixed.

**Comment by iTorongo** [comment]
@swapnildalvi2002 I have upgraded to angular 10. Please install the latest version library, it's fixed.
